# Generated by Django 3.2.18 on 2023-04-20 06:09

import Bookshelf.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('birth_year', models.DateField(blank=True, null=True, validators=[Bookshelf.models.validate_passed])),
                ('death_year', models.DateField(blank=True, null=True, validators=[Bookshelf.models.validate_passed])),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('en', 'English'), ('fa', 'Farsi'), ('fr', 'French')], max_length=2)),
                ('countries', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator('(([A-Z])\\w+[,]?)+', 'Country names should be separated by commas')], verbose_name='Countries speaking language')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='IrAuthor',
            fields=[
                ('author_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Bookshelf.author')),
                ('in_iran', models.BooleanField(verbose_name='Lives in Iran')),
            ],
            options={
                'verbose_name': 'Iranian Author',
            },
            bases=('Bookshelf.author',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('pub_date', models.DateField(blank=True, null=True, verbose_name='Publication Date')),
                ('publisher', models.CharField(blank=True, max_length=250, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Bookshelf.author')),
                ('lang', models.ManyToManyField(to='Bookshelf.Language', verbose_name='Language')),
            ],
        ),
    ]
