# Generated by Django 3.2.18 on 2023-04-20 06:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import reminder.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='User Name')),
                ('image', models.ImageField(null=True, upload_to='profile_img')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=200, null=True)),
                ('email', models.CharField(max_length=500, null=True, validators=[reminder.models.email_list])),
                ('website', models.CharField(max_length=300, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
            ],
        ),
        migrations.CreateModel(
            name='GoldUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reminder.user')),
                ('score', models.IntegerField()),
            ],
            bases=('reminder.user',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Must be unique', max_length=100)),
                ('due_date', models.DateField(null=True)),
                ('hour', models.TimeField(default='12:00:00')),
                ('category', models.CharField(choices=[('p', 'Personal'), ('w', 'Work'), ('s', 'Sport'), ('h', 'Hobby')], max_length=1, null=True)),
                ('done', models.BooleanField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reminder.user', to_field='name')),
            ],
            options={
                'db_table': 'deeds',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='HWTask',
            fields=[
            ],
            options={
                'verbose_name': 'Home Work',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reminder.task',),
        ),
        migrations.AddConstraint(
            model_name='golduser',
            constraint=models.CheckConstraint(check=models.Q(('score__gte', 5)), name='score_gte_5'),
        ),
    ]
