# Generated by Django 3.2.18 on 2023-04-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_auto_20230427_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
