# Generated by Django 3.1.1 on 2023-04-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hour',
            field=models.IntegerField(default=12),
        ),
    ]
