# Generated by Django 3.1.1 on 2023-04-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_task_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('p', 'Personal'), ('w', 'Work'), ('s', 'Sport')], max_length=1, null=True),
        ),
    ]
