# Generated by Django 3.1.1 on 2023-04-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0005_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('p', 'Personal'), ('w', 'Work'), ('s', 'Sport'), ('h', 'Hobby')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='hour',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Must be unique', max_length=100, primary_key=True, serialize=False),
        ),
    ]
