# Generated by Django 3.1.1 on 2023-04-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0009_auto_20230406_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(null=True),
        ),
    ]
