# Generated by Django 3.1.1 on 2023-04-06 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0010_auto_20230406_0806'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
