# Generated by Django 3.1.1 on 2023-04-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0013_auto_20230406_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
